### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by RockZhou8** [sagaxu/lagou-finder#3]
我想自己改地方：改到上海 杭州深圳什么的，职位改前端 安卓什么的
运行webapp，都还是北京，于是运行finder.py
装的是python2 结果No module named queue
改装了python3，运行py -3 finder.py ，结果如下
'content'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "finder.py", line 25, in geo_worker
    address = LagouAPI.get_location_by_pos_id(jd['positionId'])
  File "C:\Study\lagou-finder-master\LagouAPI.py", line 53, in get_location_by_pos_id
    corp_info = soup.select('#container > div.content_r > dl > dd')[0]
IndexError: list index out of range

**Comment by RockZhou8** [comment]
lastest version works fine in Arch Linux!
Good Job!
btw. close issue...
